const cards = [
    {
        "id": 0,
        "fullname": "amigos",
        "description": "La clave esta en saber disimular...por lo visto no es tu fuerte",
        "images": "../images/amigos.jfif",
    },
    {
     "id": 1,
     "fullname": "bello",
     "description": "Esta semana te vas a sentir mas hermos@ que nunca!",
     "images": "../images/bello.jpg",
    },
    {
        "id": 2,
        "fullname": "buenas decisiones",
        "description": "Deberias de pensarlo dos veces, antes de hacerlo",
        "images": "../images/buenasdecisiones.jpg",
       },
       {
        "id": 3,
        "fullname": "deudas",
        "description": "Deberias medir tus gastos...ya no te va a alcanzar para el guiso",
        "images": "../images/deudas.jfif",
       },
       {
        "id": 4,
        "fullname": "dormir",
        "description": "Estas acostandote muy tarde, mañana ni a escobazos te levantan",
        "images": "../images/dormir.jfif",
       },
       {
        "id": 5,
        "fullname": "enfermedad",
        "description": "Esta semana deberias cuidarte mas, no te confies!",
        "images": "../images/enfermedad.jpg",
       },
       {
        "id": 6,
        "fullname": "estudiar",
        "description": "Ponete las pilas y dejar de ver tik toks!",
        "images": "../images/estudiar.jpg",
       },
       {
        "id": 7,
        "fullname": "familia traicion",
        "description": "Tene cuidado en la flia...nunca se sabe (ojo con el tio Nacho)",
        "images": "../images/familiatraicionera.jpg",
       },
       {
        "id": 8,
        "fullname": " fin de semana",
        "description": "Recorda que tambien es valido descansar!",
        "images": "../images/findesemana.jpg",
       },
       {
        "id": 9,
        "fullname": "ingles",
        "description": "No dejes para mañana, lo que podes aprender hoy, despues a llorar a la iglesia",
        "images": "../images/ingles.jfif",
       },
       {
        "id": 10,
        "fullname": "Mala semana",
        "description": "Esta semana viene complicadita, ojo!",
        "images": "../images/malasemana1.jfif",
       },
       {
        "id": 11,
        "fullname": "Se viene el finde",
        "description": "Se viene el finde ponete las pilas, que despues al mati lo quieren colgar",
        "images": "../images/malasemana.jpg",
       },
       {
        "id": 12,
        "fullname": "No entiendo",
        "description": "Esta semana se viene jodida, presta atencion!",
        "images": "../images/noentiendo.jfif",
       },
       {
        "id": 13,
        "fullname": "Novia enojada",
        "description": "esta semana tene cuidado con lo que decis...te va a salir caro pifiarla",
        "images": "../images/noviaenojada.jpg",
       },
       {
        "id": 14,
        "fullname": "Paciencia",
        "description": "La paciencia no es tu fuerte...respira profundo y no mandes a nadie a la mier..",
        "images": "../images/paciencia.jpg",
       },
       {
        "id": 15,
        "fullname": "Panza llena",
        "description": "Esta semana vas a tener que aprender a decir que no!",
        "images": "../images/panzallena.jpg",
       },
       {
        "id": 16,
        "fullname": "Prestamo",
        "description": "Ojo con los que aparecen de la nada, seguro te quieren manguear algo",
        "images": "../images/prestamo.jfif",
       },
       {
        "id": 17,
        "fullname": "Programacion",
        "description": "Parece facil, no te confies, practica",
        "images": "../images/programacion.jpg",
       },
       {
        "id": 18,
        "fullname": "Programacion Avanzada",
        "description": "Y que aprendiste el Winter?",
        "images": "../images/programarmemes.jpg",
       },
       {
        "id": 19,
        "fullname": "La salud",
        "description": "Procura alimentarte bien, tampoco te bajes todos los bizcochitos don satur!",
        "images": "../images/salud.jfif",
       },
       {
        "id": 20,
        "fullname": "Sentimientos",
        "description": "Esta semana tene cuidado con tu pareja, te puede tirar +4!",
        "images": "../images/sentimientos.jpg",
       },
       {
        "id": 21,
        "fullname": "Al que madruga...",
        "description": "Deja de viciar y acostate temprano, que despues no te despierta ni tu vieja",
        "images": "../images/temprano.jpg",
       },
       {
        "id": 22,
        "fullname": "Vistima",
        "description": "Recorda no hacerte siempre el Neimar, usa bien esa carta",
        "images": "../images/vistima.jpg",
       },
]